# Generated by Django 3.2.7 on 2021-10-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_gql', models.CharField(max_length=255)),
                ('nombre_gql', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SociedadAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('estatuto', models.FileField(upload_to='')),
                ('domicilio_real', models.CharField(max_length=255)),
                ('domicilio_legal', models.CharField(max_length=255)),
                ('email_apoderado', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SocioSociedadAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('porcentaje_aporte', models.FloatField()),
                ('sociedad', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.sociedadanonima')),
            ],
        ),
        migrations.AddField(
            model_name='sociedadanonima',
            name='apoderado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.sociosociedadanonima'),
        ),
        migrations.AddField(
            model_name='sociedadanonima',
            name='paises_exporta',
            field=models.ManyToManyField(to='models.Pais'),
        ),
    ]
