# Generated by Django 3.2.7 on 2021-10-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20211002_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sociedadanonima',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sociosociedadanonima',
            options={},
        ),
        migrations.AlterModelTable(
            name='pais',
            table='Pais',
        ),
        migrations.AlterModelTable(
            name='sociedadanonima',
            table='SociedadAnonima',
        ),
        migrations.AlterModelTable(
            name='sociosociedadanonima',
            table='SocioSociedadAnonima',
        ),
    ]
